### PR TITLE
added home page template

### PR DESCRIPTION
**Pull request by Hnh013**
added home page
added home page images 
added basic styles

### CODE REVIEW

**Review by Sharmaa-Ansh — APPROVED** [review]

**Review by hrishi82 — APPROVED** [review]
Suggestion: 
Maybe try to decrease the size of the icons in the navigation bar. 
Its totally understandable if that's the style you're going for, so its upto you

Rest looks good!

**Review by SJTGSHIVAM — APPROVED** [review]
Code looks good just a suggestion you can convert jpegs to webp format it will be lighter.
rest we are good to merge.

**Comment by Hnh013** [comment]
> Code looks good just a suggestion you can convert jpegs to webp format it will be lighter. rest we are good to merge.

converted , thanks for the suggestion

**Comment by Hnh013** [comment]
> Suggestion: Maybe try to decrease the size of the icons in the navigation bar. Its totally understandable if that's the style you're going for, so its upto you
> 
> Rest looks good!

thanks Hrishi , will try to manage , between the badge size and material icon size

**Pull request merged**
