### PR TITLE
added logout page and fixed bugs

### PR DESCRIPTION
**Pull request by Hnh013**
added logout page
fixed minor bugs

### CODE REVIEW

**Review by romabulani — APPROVED** [review]
Good use of semantic tags, looks good to merge

**Review by romabulani — APPROVED** [review]
Looks good to merge

**Review by Aman-Jain1996 — APPROVED** [review]
Just one recommendation , remove signUp link from logout page bcz , a user who has login can only logout and be there or that logout page , no sense for adding signUp link there

**Review by shilpe26 — APPROVED** [review]
Code looks good to merge

**Review by mdarif6 — APPROVED** [review]
looks good to merge

**Comment by Hnh013** [comment]
> Just one recommendation , remove signUp link from logout page bcz , a user who has login can only logout and be there or that logout page , no sense for adding signUp link there

thanks Aman will resolve that

**Pull request merged**
